export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_DIETS = 'GET_DIETS'
export const RECIPE_DETAIL = 'RECIPE_DETAIL';
export const CREATE_RECIPE = 'CREATE_RECIPE';

export const SEARCH_RECIPE_BY_NAME = 'SEARCH_RECIPE_BY_NAME';
export const SEARCH_RECIPE_BY_DIET = 'SEARCH_RECIPE_BY_DIET';

export const ALPHABETIC_ORDER = 'ALPHABETIC_ORDER';
export const SCORE_ORDER = 'SCORE_ORDER';

export const SELECT_PAGE = 'SELECT_PAGE';

export const ERROR = 'ERROR';